### ISSUE TITLE
Controllers should be loaded after plugins and middleware

### ISSUE THREAD

**Issue by carlos8f** [cantina/cantina-web#1]
I found that if I write a plugin to add `app.something` and then I try to use `app.something` in a controller, it is undefined. It appears that controllers are loaded as a plugin with other plugins, so the load order of controllers is undefined vs plugins. Further, middleware is loaded after controllers, which is backward IMO.

In motley I took care to have a strict load order, so one layer can predictably build off other layers (and not have to `require()` except for special cases) and I suggest the same for cantina:
1. core plugins
2. user plugins
3. core middleware
4. user middleware
5. user controllers

**Comment by cpsubrian** [comment]
I kinda have to take your word for it here .. but AFAIK controllers load last.

**Comment by cpsubrian** [comment]
Will investigate though

**Comment by carlos8f** [comment]
it's easy to see if you place a console.log at the top of each type of file. I did it in scorecards-www, and it goes:
1. controller
2. plugin
3. middleware

**Comment by cpsubrian** [comment]
Agreed, then, that it should be (by default, these things are all weightable):
1. Plugin
2. Middleware
3. Controller

**Comment by cpsubrian** [comment]
Will tackle this when I have a change to breath (unless its causing a critical bug?)

**Comment by carlos8f** [comment]
not critical, since you can require() the plugins/middleware you need at the top of your controller. just a bit of a regression to 2.x style.

**Comment by cpsubrian** [comment]
Resolved by c1ca4a15e25e8b0ead2d6d94c20ea4a6ec4300b6

'published' as v3.1.0 and merged into 3.x branch. I chose to use a minor version since its behavior is different, thus it could break code that assumed the old load order.
