### ISSUE TITLE
Delay loading

### ISSUE THREAD

**Issue by danmactough** [cantina/cantina-web#6]
Some quick pseudo-code and bullet points to memorialize a conversation @cpsubrian and I had about a circular dependency nightmare we encountered while refactoring KeyVote to use the new cantina user system.
## Problem
- cantina-web loads its own default middleware as well as the app's middleware (and controllers and views)
- this causes a problem if any plugin you require, directly or indirectly, requires cantina-web before you're ready

Example: cantina/cantina-app-users#15
## Solution

Calling `require('cantina-web')` to ensure that the API it exposes is available, for example in a plugin, should not cause the loaders to actually load.

Instead, cantina should expose a loader API that cantina-web and other cantina plugin use to register load methods that can be manually invoked either by the app or other plugins.
## Pseudo-code

Cantina would define something like this:

``` js

app.boot = function (root, callback) {
  // ...
  app.loader = Object.create(Object.prototype, {
    _loaders: {
      value: {},
      writable: true
    },
    add: {
      value: function (name, fn) {
        this._loaders[name] = fn;
      },
      enumerable: true
    },
    load: {
      value: function () {
        Object.keys(this._loaders).forEach(function (name) {
          this._loaders[name]();
        }, this);
      },
      enumerable: true
    }
  });
};
```

And then `cantina-web.js` would change to something like this:

``` js
var app = require('cantina');

// Load local plugins.
app.load('plugins', __dirname);
// Probably not doing this anymore
// app.load('plugins'); 

// Register the app views.
app.loader.add('views', function () {
  app.loadViews('views');
});

// Register the app static files.
app.loader.add('static', function () {
  app.loadStatic('public');
});

// Register the local and app middleware.
app.loader.add('middleware', function () {
  app.loadMiddleware('middleware', __dirname);
  app.loadMiddleware('middleware');
});

// Register the app controllers.
app.loader.add('controllers', function () {
  app.loadControllers('controllers');
});
```

And finally, in your `app.js` you'd do something like this:

``` js
var app = require('cantina');

app.boot(function (err) {
  if (err) throw err;

  require('cantina-web');
  app.load('plugins');
  app.loaders.load();

  app.start();
});
```

**Comment by cpsubrian** [comment]
### Foreword

Zen Mode FTW! 

Not using any fancy `Object.create()` fu here, but feel free to if you think it adds utility/stability.

Not 100% on the API interface ... I like `app.loaders.add('emails', //...` but I don't like the idea of a bunch of `app.loaders.load('emails')` calls.

Thoughts?

### cantina

``` js
// Module for getting callstack info, haven't really evaluated it yet.
var callerId = require('caller-id');

// Private registry of loaders
app._loaders = {};

// Add a loader.
app.loader = function (type, handler) {
  app._loaders[type] = handler;
};

// Run a loader. Usually called with no 'parent' or 'dir' options.
app.load = function (type, options) {
  if (!app._loaders[type)) throw new Error('Doh!');

  options = options || {};
  if (!options.parent) {
    options.parent = path.dirname(callerId.getData().filePath);
  }
  if (!options.dir) {
    options.dir = type;
  }
  options.path = path.resolve(options.parent, options.dir);

  app._loaders[type](options);
};

// Register 'modules' type loader.
app.loader('modules', function (options) {
  var modules = {};

  // Load .js files in the directory.
  glob.sync(options.path + '/*.js').forEach(function (p) {
    modules[path.basename(p, '.js')] = require(path.resolve(p));
  });

  // Load index.js files one level down.
  glob.sync(options.path + '/**/index.js').forEach(function (p) {
    modules[path.dirname(p).split('/').pop()] = require(path.resolve(p));
  });

  return modules;
});

// Register a plugins loader.
app.loader('plugins', function (options) {
  options.dir = 'plugins';
  app.load('modules', options);
});
```

### Example implementation: cantina-email

``` js
app.loader('emails', function (options) {
  app.hook('email:load:templates').add(options.weight || 0, function loadTemplateDir (done) {
      if (fs.existsSync(options.path)) {
        glob.sync('**/*.md', {cwd: options.path}).forEach(function (file) {
          var template = loadTemplate(path.resolve(options.path, file), 'text');
          Object.keys(template).forEach(function (k) {
            if (typeof template[k] === 'string') {
              template[k] = handlebars.compile(template[k]);
            }
          });
          app.email.templates[file.replace(/\.md$/, '')] = template;
        });
      }
      done();
    }
  );
});
```

### Example app:

``` js
var app = require('cantina');

app.boot(function (err) {
  if (err) throw err;

  require('cantina-web');
  require('cantina-email');

  app.load('plugins');
  app.load('static');
  app.load('emails');
  app.load('views');
  app.load('middleware');
  app.load('controllers');

  // Load extra views folder.
  app.load('views', {dir: 'extraViews'});

  app.start();
});
```

### Possible cantina-web helper.

Not sure how to get around elimination of per-loader options.

``` js
app.loader('web', function (options) {
  app.load('plugins', {parent: options.parent});
  app.load('static', {parent: options.parent});
  app.load('views', {parent: options.parent});
  app.load('middleware', {parent: options.parent});
  app.load('controllers', {parent: options.parent});
});
```

**Comment by cpsubrian** [comment]
Realized the emails one above is incomplete ... never runs the hook ... but assumed that would be on app start.

**Comment by cpsubrian** [comment]
If we wanted to get really crazy .. the above might transform into:

``` js
// Do it manually (because order of emails matters).
app.load('web:plugins');
app.load('web:static');
app.load('web:views');
app.load('emails');
app.load('web:middleware');
app.load('web:controllers');

// Use the helper, because order doesn't matter.
app.load('web');
app.load('emails');
```

**Comment by danmactough** [comment]
This might be too much into the weeds, but I don't know about that example implementation for emails. Why would your loader to nothing but register a stact? How is that any better than just:

``` js
var app = require('cantina');

app.hook('email:load:templates').add(options.weight || 0, function loadTemplateDir (done) {
    if (fs.existsSync(options.path)) {
      glob.sync('**/*.md', {cwd: options.path}).forEach(function (file) {
        var template = loadTemplate(path.resolve(options.path, file), 'text');
        Object.keys(template).forEach(function (k) {
          if (typeof template[k] === 'string') {
            template[k] = handlebars.compile(template[k]);
          }
        });
        app.email.templates[file.replace(/\.md$/, '')] = template;
      });
    }
    done();
  }
);
```

Other than that, the API looks fine.

### Quesitons
1. What should happen when you define the same loader more than once? Throw? Add? Override? (I think add.)
2. Why can't I think of any more questions?

**Comment by cpsubrian** [comment]
> How is that any better than just:

The point of the loader is to abstract the loading away. Without the loader you have to supply options.path, making loading emails different from loading everything else.

More to the point, emails wraps its loading in a stact hook for some reason I can't think of right now. Help me, @erinlesavoy!

> What should happen when you define the same loader more than once? Throw? Add? Override? (I think add.)

Throw I think. The point of a loader is 'tell me how to load a directory of special stuff'. If we want some kind of a loader 'pipeline' (ala browserify or w/e), that would look quite a bit different.

**Comment by erindethorne** [comment]
Emails wraps it's loading in the start hook to allow plugins to "register"
their email template dirs with stac weights (I think). Then we wait until
start to do the loading so we know all plugins that want to have
registered.

**Comment by erindethorne** [comment]
Maybe this could be refactored too though.

**Comment by cpsubrian** [comment]
> Maybe this could be refactored too though.

Ahh, yes, I remember now. Perhaps our loader api should support 'delayed' loaders (that support weights). Not sure how you'd tell the difference (or if it matters).

**Comment by cpsubrian** [comment]
This has been implemented .. for a while :)

**Comment by danmactough** [comment]
Blast from the past!

**Comment by cpsubrian** [comment]
Sorry, not sorry :)

**Comment by cpsubrian** [comment]
I still think this is the best web framework :stuck_out_tongue_winking_eye:

**Comment by danmactough** [comment]
Needs generators. And promises.
